### ISSUE TITLE
Raw data

### ISSUE THREAD

**Issue by aechchiki** [afranks86/tissue-ptr#1]
Hi @afranks86 .

I am interested in your methodology, possibly to push further some analysis. For the moment, I am trying to replicate your analysis. 

From your paper, I read that you used RNA-seq data from:
- Djebali et al. 2012 (GSE26284, GSE33480, GSE24565, GSE33600, GSE34448) - the one you refer to as 'Illumina data' in your script `preprocess_mrna.R`
- Fagerberg et al. 2014 (E-MTAB-1733) - the one you refer to as 'ProteinAtlas data' in your script `preprocess_mrna.R`

I am not sure which files you used for processing, respectively (I guess) the files:
- `Illumina/Illumina_FPKM_allsamples.txt`
- `ProteinAtlas/transcript_rna_tissue.tsv` 

Could you please tell where did you get these dataset you are referring to?

Many thanks
Amina

**Comment by afranks86** [comment]
@aechchiki,

Thanks for asking! The raw data can be accessed using this Dropbox link: https://www.dropbox.com/sh/4nzzqtsoixsh5gm/AAAMtqZ9qU8F1ggyaIM9prqKa?dl=0

This should include the raw data for both mRNA and protein data.   I'll make a note about this link in the README as well.  

Let me know if you have other questions.

**Comment by aechchiki** [comment]
Thank you!
